'use strict';

angular.module('app.communication').constant(
  'CommunicationEvents',
  {
    user : {
      _SYNC_GET_CURRENT_USER_ : '_SYNC_GET_CURRENT_USER_',
      _SYNC_GET_CURRENT_USER_START_ : '_SYNC_GET_CURRENT_USER_START_',
      _SYNC_GET_CURRENT_USER_COMPLETE_ : '_SYNC_GET_CURRENT_USER_COMPLETE_',
      _SYNC_GET_CURRENT_USER_FAIL_ : '_SYNC_GET_CURRENT_USER_FAIL_',

      _AUTHENTICATE_ : '_AUTHENTICATE_',
      _AUTHENTICATE_START_ : '_AUTHENTICATE_START_',
      _AUTHENTICATE_COMPLETE_ : '_AUTHENTICATE_COMPLETE_',
      _AUTHENTICATE_FAIL_ : '_AUTHENTICATE_FAIL_',

      _REGISTER_ : '_REGISTER_',
      _REGISTER_START_ : '_REGISTER_START_',
      _REGISTER_COMPLETE_ : '_REGISTER_COMPLETE_',
      _REGISTER_FAIL_ : '_REGISTER_FAIL_',

      _LOGOUT_ : '_LOGOUT_',
      _LOGOUT_START_ : '_LOGOUT_START_',
      _LOGOUT_COMPLETE_ : '_LOGOUT_COMPLETE_',
      _LOGOUT_FAIL_ : '_LOGOUT_FAIL_',

      _SYNCED_ : '_SYNCED_'
    },
    room : {
      _CREATE_ : '_CREATE',
      _CREATE_START_ : '_CREATE_START_',
      _CREATE_COMPLETE_ : '_CREATE_COMPLETE_',
      _CREATE_FAIL_ : '_CREATE_FAIL_'
    }
  }
);
